apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "steampipe-platform.fullname" . }}-powerpipe
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "steampipe-platform.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powerpipe
  template:
    metadata:
      labels:
        app: powerpipe
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.powerpipe.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: powerpipe
          {{- with .Values.powerpipe.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ .Values.powerpipe.image }}
          {{- with .Values.powerpipe.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.powerpipe.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.powerpipe.port }}
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "steampipe-platform.dbAppSecretName" . }}
                  key: password
          {{- with .Values.powerpipe.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}