apiVersion: v1
kind: Service
metadata:
  name: {{ include "steampipe-platform.fullname" . }}-powerpipe
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "steampipe-platform.labels" . | nindent 4 }}
spec:
  selector:
    app: powerpipe
  ports:
    - port: {{ .Values.powerpipe.port }}
      targetPort: {{ .Values.powerpipe.port }}