{{/*
Expand the name of the chart.
*/}}
{{- define "steampipe-platform.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "steampipe-platform.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "steampipe-platform.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "steampipe-platform.labels" -}}
helm.sh/chart: {{ include "steampipe-platform.chart" . }}
{{ include "steampipe-platform.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "steampipe-platform.selectorLabels" -}}
app.kubernetes.io/name: {{ include "steampipe-platform.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Database cluster name
*/}}
{{- define "steampipe-platform.dbClusterName" -}}
{{- .Values.database.clusterName }}
{{- end }}

{{/*
Database app secret name (auto-generated by CNPG)
*/}}
{{- define "steampipe-platform.dbAppSecretName" -}}
{{- printf "%s-app" .Values.database.clusterName }}
{{- end }}

{{/*
Database superuser secret name (auto-generated by CNPG)
*/}}
{{- define "steampipe-platform.dbSuperuserSecretName" -}}
{{- printf "%s-superuser" .Values.database.clusterName }}
{{- end }}

{{/*
Database RW service hostname
*/}}
{{- define "steampipe-platform.dbHost" -}}
{{- printf "%s-rw.%s.svc.cluster.local" .Values.database.clusterName .Values.namespace }}
{{- end }}

{{- define "steampipe-platform.searchPath" -}}
cache,
{{- if .Values.providers.aws }}
{{- if .Values.providers.aws.accounts }} aws_all,
{{- range .Values.providers.aws.accounts }} aws_{{ .name }},
{{- end }}
{{- else }} aws,
{{- end }}
{{- end }}
{{- if .Values.providers.gcp }}
{{- if .Values.providers.gcp.projects }} gcp_all,
{{- range .Values.providers.gcp.projects }} gcp_{{ .name }},
{{- end }}
{{- else }} gcp,
{{- end }}
{{- end }}
{{- if .Values.providers.kubernetes }}
{{- if .Values.providers.kubernetes.clusters }} k8s_all,
{{- range .Values.providers.kubernetes.clusters }} k8s_{{ .name }},
{{- end }}
{{- else }} k8s,
{{- end }}
{{- end }} public
{{- end }}

