apiVersion: v1
kind: ConfigMap
metadata:
  name: powerpipe-config
  namespace: steampipe
data:
  steampipe.ppc: |
    connection "postgres" "default" {
      host     = "steampipe-db-rw.steampipe.svc.cluster.local"
      port     = 5432
      db       = "steampipe"
      username = "steampipe"
      password = env("PGPASSWORD")
      search_path = ["cache", "aws", "public"]
    }