apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerpipe
  namespace: steampipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powerpipe
  template:
    metadata:
      labels:
        app: powerpipe
    spec:
      containers:
        - name: powerpipe
          image: eliaz133/powerpipe:0.1.0
          ports:
            - containerPort: 9033
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: steampipe-db-app
                  key: password
            - name: POWERPIPE_DATABASE
              value: "postgresql://steampipe:$(PGPASSWORD)@steampipe-db-rw.steampipe.svc.cluster.local:5432/steampipe"
            - name: POWERPIPE_INSTALL_DIR
              value: "/tmp/powerpipe"
          volumeMounts:
            - name: powerpipe-config
              mountPath: /tmp/powerpipe/config/steampipe.ppc
              subPath: steampipe.ppc
      volumes:
        - name: powerpipe-config
          configMap:
            name: powerpipe-config